apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-broker
  namespace: {{ .Values.namespaces.ours }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-broker
  template:
    metadata:
      labels:
        app: mqtt-broker
    spec:
      containers:
        - name: mosquitto
          image: {{ .Values.mqtt.image }}
          ports:
            - containerPort: {{ .Values.mqtt.port }}
              name: mqtt
            - containerPort: {{ .Values.mqtt.websocketPort }}
              name: websocket
          volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config
