apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-fhir-server
  namespace: {{ .Values.namespace }}
  labels:
    app: mock-fhir-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-fhir-server
  template:
    metadata:
      labels:
        app: mock-fhir-server
    spec:
      containers:
        - name: mock-fhir-server
          image: {{ .Values.mockFhir.image }}
          imagePullPolicy: {{ .Values.mockFhir.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.mockFhir.port }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.mockFhir.port }}
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.mockFhir.port }}
            initialDelaySeconds: 15
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: mock-fhir-server
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mock-fhir-server
  ports:
    - port: {{ .Values.mockFhir.port }}
      targetPort: {{ .Values.mockFhir.port }}
      protocol: TCP
