apiVersion: v1
kind: Secret
metadata:
  name: fall-detection-secrets
  namespace: {{ .Values.namespaces.ours }}
type: Opaque
stringData:
  postgres-password:    {{ .Values.postgres.password | quote }}
  minio-root-password:  {{ .Values.minio.rootPassword | quote }}
  api-keys:             {{ .Values.inferenceServer.apiKeys | quote }}
  grafana-admin-password: {{ .Values.grafana.adminPassword | quote }}
