apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: {{ .Values.namespaces.ours }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: {{ .Values.grafana.image }}
          ports:
            - containerPort: {{ .Values.grafana.port }}
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fall-detection-secrets
                  key: grafana-admin-password
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
            - name: GF_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fall-detection-secrets
                  key: postgres-password
          resources:
            requests:
              cpu:    {{ .Values.resources.grafana.requests.cpu }}
              memory: {{ .Values.resources.grafana.requests.memory }}
            limits:
              cpu:    {{ .Values.resources.grafana.limits.cpu }}
              memory: {{ .Values.resources.grafana.limits.memory }}
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
            - name: grafana-provisioning
              mountPath: /etc/grafana/provisioning
              readOnly: true
            - name: grafana-dashboards
              mountPath: /var/lib/grafana/dashboards
              readOnly: true
      volumes:
        - name: grafana-data
          emptyDir: {}
        - name: grafana-provisioning
          configMap:
            name: grafana-provisioning
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards
