apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Values.namespaces.ours }}
spec:
  selector:
    app: grafana
  ports:
    - port: {{ .Values.grafana.port }}
      targetPort: {{ .Values.grafana.port }}
