apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: {{ .Values.namespaces.ours }}
spec:
  selector:
    app: minio
  ports:
    - name: s3
      port: {{ .Values.minio.port }}
      targetPort: {{ .Values.minio.port }}
    - name: console
      port: {{ .Values.minio.consolePort }}
      targetPort: {{ .Values.minio.consolePort }}
  clusterIP: None
