apiVersion: v1
kind: Service
metadata:
  name: server-health
  namespace: {{ .Values.namespaces.ours }}
spec:
  selector:
    app: server-health
  ports:
    - port: {{ .Values.serverHealth.port }}
      targetPort: {{ .Values.serverHealth.port }}
