apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data
  namespace: {{ .Values.namespace }}
  labels:
    app: mosquitto
    {{- include "caregiver.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mosquitto.persistence.size }}
  {{- if .Values.mosquitto.persistence.storageClass }}
  storageClassName: {{ .Values.mosquitto.persistence.storageClass }}
  {{- end }}
