apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: {{ .Values.namespace }}
  labels:
    app: mosquitto
    {{- include "caregiver.labels" . | nindent 4 }}
data:
  mosquitto.conf: |
    {{- .Values.mosquitto.config | nindent 4 }}
